### ISSUE TITLE
Add Support for mongoid

### ISSUE THREAD

**Issue by quorak** [waiting-for-dev/devise-jwt#100]
hey there, thanks for the great gem.

I use devise with mongoid as persistence layer. 2 pitfalls I came across so far:

* `update_columns` does not work as expected in mongoid
* `primary_key` does not exist on the user model

As device supports a mongoid setup, it would be great to support it with devise-jwt as well.

I will keep u updated about further findings.

**Comment by waiting-for-dev** [comment]
Hi @quorak ,

when I first developed the gem I was reluctant to add support to more ORM. I want to keep this gem simple, and it is not difficult to just create new models/revocation strategies.

But as you say, mongoid is supported out of the box by devise, so it could be nice to support it as well. At least, we could adapt the `jwt_authenticatable` model if it is possible, or create a new one just for mongoid. I don't mind too much about the revocation strategies, because the ones shipped in the gem are there mainly to illustrate how to create new ones through custom revocation strategies.

I'm not familiar with mongoid, which changes would be necessary in order to adapt it?

**Comment by coolmate** [comment]
This is exactly I am looking for, to support the mongo db

**Comment by quorak** [comment]
I was able to get the basic exmaple working by adding the required class methods
``` ruby
class User
  include Mongoid::Document
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable,
         :jwt_authenticatable, jwt_revocation_strategy: self


[...]


  def self.primary_key
    '_id'
  end

  def self.revoke_jwt(_payload, user)
    user.update_attribute(:jti, generate_jti)
  end
end
```

to the devise enabled models. Have not tested all edge cases though. Hope this helps someone.

**Comment by waiting-for-dev** [comment]
Is the AR API used in `Devise::JWT::RevocationStrategies::JTIMatcher` 100% compatible with mongoid?

**Comment by waiting-for-dev** [comment]
It would be interesting to adapt the gem to mongoid. However, I haven't worked with it so I'm not going to do it for now. If somebody is interested in working on this I'll reopen this issue and offer all the guidance nedded.

**Comment by gitadam0** [comment]
any updates?
