### ISSUE TITLE
authenticate_scope! not verifying for :edit, :update and :delete

### ISSUE THREAD

**Issue by jovanmaric** [waiting-for-dev/devise-jwt#105]
## Expected behavior
The authenticate_scope! in the devise RegistrationsController should pass when a valid JWT is applied to the header. This applies to the edit, update and delete action.

## Actual behavior
The response is handled immediately by the devise failure app. Resulting in a 401 status instead of the expected 204 status (see git repo).

## Steps to Reproduce the Problem
The error can be reproduced with the following repository: https://github.com/jovanmaric/devise-jwt-demo, which consists of my current config and devise controller rewrite.

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use
0.5.8
- Version of `rails` in use
5.2.0
- Output of `Devise::JWT.config`
```
#<#<Class:0x000055d82571ed98>:0x000055d82571e460
 @config=
  {:secret=>"9cfb4df759a6abde13d6c7afe388154eca045c48c535650771897a03f60b5cbe747820e016b9cd11bb770bdcf2ef19d03f45759ba5c556b4c86a840d650119b4",
   :expiration_time=>nil,
   :dispatch_requests=>nil,
   :revocation_requests=>nil,
   :aud_header=>nil,
   :request_formats=>{}}>
```
- Output of `Warden::JWTAuth.config`
```
#<#<Class:0x000055d824e770f0>:0x000055d824e76240
 @config=
  {:secret=>"9cfb4df759a6abde13d6c7afe388154eca045c48c535650771897a03f60b5cbe747820e016b9cd11bb770bdcf2ef19d03f45759ba5c556b4c86a840d650119b4",
   :expiration_time=>3600,
   :aud_header=>"JWT_AUD",
   :mappings=>{:user=>"User"},
   :dispatch_requests=>[["POST", /^\/api\/users\/sign_in$/], ["POST", /^\/api\/users\/$/]],
   :revocation_requests=>[["DELETE", /^\/api\/users\/sign_out$/]],
   :revocation_strategies=>{:user=>"User"}}>
```
- Output of `Devise.mappings`
```
{:user=>
  #<Devise::Mapping:0x000055d823aac160
   @class_name="User",
   @controllers={:registrations=>"api/users/registrations", :sessions=>"devise/sessions", :passwords=>"devise/passwords", :confirmations=>"devise/confirmations"},
   @failure_app=Devise::FailureApp,
   @format=nil,
   @klass=#<Devise::Getter:0x000055d823aa8ab0 @name="User">,
   @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :lockable, :timeoutable, :trackable, :jwt_authenticatable],
   @path="api/users/",
   @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation"},
   @path_prefix=nil,
   @router_name=nil,
   @routes=[:session, :password, :registration, :confirmation, :unlock],
   @scoped_path="users",
   @sign_out_via=:delete,
   @singular=:user,
   @used_helpers=[:session, :password, :registration, :confirmation, :unlock],
   @used_routes=[:session, :password, :registration, :confirmation]>}
```
- If your issue is related with not getting a JWT from the server:
  - Involved request path, method and request headers
  - Response headers for that request
- If your issue is related with not being able to revoke a JWT:
  - Involved request path, method and request headers

**Comment by waiting-for-dev** [comment]
My first guess is that devise method `authenticate_scope!` won't work because you have session disabled. That method tries [to get the user from the session](https://github.com/plataformatec/devise/blob/acc45c5a44c45b252ccba65fd169a45af73ff369/app/controllers/devise/registrations_controller.rb#L134), so if you don't have sessions a low level usage of that method won't work.

If it doesn't help I'll try to reproduce the issue with your repo. But first, please, could you change it to use `sqlite` instead of `pg` so that I don't have to deal with database servers (or, otherwise, a dockerized env would be fine for me)?

**Comment by jovanmaric** [comment]
> My first guess is that devise method authenticate_scope! won't work because you have session disabled. That method tries to get the user from the session, so if you don't have sessions a low level usage of that method won't work.

Doesn't the current_user for instance get initialized with the jwt devise strategy? Considering that otherwise, the current_user can't be used anywhere in the code. Which would break common devise functionality?

> If it doesn't help I'll try to reproduce the issue with your repo. But first, please, could you change it to use sqlite instead of pg so that I don't have to deal with database servers (or, otherwise, a dockerized env would be fine for me)?

I'm not really familiar with sqlite. Would adding a Dockerfile to the repo be sufficient perhaps?

**Comment by waiting-for-dev** [comment]
> Doesn't the current_user for instance get initialized with the jwt devise strategy? Considering that otherwise, the current_user can't be used anywhere in the code. Which would break common devise functionality?

I was confused by the method comments in devise repo. Now I see it just calls `current_user`, and this method behaviour is not changed by `devise-jwt`.

> I'm not really familiar with sqlite. Would adding a Dockerfile to the repo be sufficient perhaps?

Well, a `Dockerfile` and a `docker-compose.yml` file, in order to glue de database service. But if you are not familiar with this, no worries. I'll change `pg` for `sqlite` myself.

But, anyway, let's try first some debugging from here.

One thing I see in your repo is you have two `ApplicationController`. One on [top namespace](https://github.com/jovanmaric/devise-jwt-demo/blob/master/app/controllers/application_controller.rb) and another within [`Api` namespace](https://github.com/jovanmaric/devise-jwt-demo/blob/master/app/controllers/api/application_controller.rb). If I'm not wrong (you can check it with `ancestors` method), your `RegistrationsController` inherits from the first, which is not responding to `:json`.

> The authenticate_scope! in the devise RegistrationsController should pass when a valid JWT is applied to the header. This applies to the edit, update and delete action.

So, if I understand, you say that JWT authentication is not working in `RegistrationsController` but it works elsewhere. Could you copy here an exampe request/response (URL, params, headers...) of an example where it is working and an example where it isn't?

**Comment by waiting-for-dev** [comment]
Is there still an issue here?

**Comment by jovanmaric** [comment]
I'm sorry, I totally forgot to answer. 

> One thing I see in your repo is you have two ApplicationController. One on top namespace and another within Api namespace. If I'm not wrong (you can check it with ancestors method), your RegistrationsController inherits from the first, which is not responding to :json.

This is indeed an error on my end, and should be as you said.

> So, if I understand, you say that JWT authentication is not working in RegistrationsController but it works elsewhere. Could you copy here an exampe request/response (URL, params, headers...) of an example where it is working and an example where it isn't?

After some trial and error I noticed that in the above demo code the error was formed by not confirming the devise resource, while having the :confirmable module included. This resulted in the test failing, as devise does not allow unconfirmed accounts to login. The devise-jwt helper did however still create a JWT, even though the resource wasn't confirmed. This could be made explicit, when creating a jwt token with the testhelper. 

Yet this didn't fix the issue in my application. The problem there was formed by including the session and cookie modules into rails, while having api_only mode enabled. I had been meddling with a way to save the jwt inside a http_only cookie, and forgot to remove these modules. Devise therefore defaulted all warden authentication to the database_authenticatable strategy (instead of the JWT one). Making the JWT auth useless.  

This issue is therefore solved.

**Comment by waiting-for-dev** [comment]
Ok, happy it works now.
