### ISSUE TITLE
Syntax error on `jwt_authenticatable` and `jwt_revocation_strategy`

### ISSUE THREAD

**Issue by jfloff** [waiting-for-dev/devise-jwt#108]
## Expected behavior

I was following the provided steps on the README, but I appear to have a very dumb error. I bet its probably something on my end, but I can't seem to figure this one out. I'm sorry in advance if this is something very basic.

## Actual behavior

When I'm setting my class devise settings, like this:
```
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: [:facebook],
         :jwt_authenticatable, jwt_revocation_strategy: JWTBlacklist
```

I get a syntax error, like this: 

```
/app/user/app/models/user.rb:76: syntax error, unexpected ',', expecting =>
         :jwt_authenticatable, jwt_revocation_strategy: JWTB
                              ^ (SyntaxError)
```

I'm really clueless on what's happening

## Debugging information

- Version of `devise-jwt`: `0.5.8`
- Version of `rails`: `4.2.9`

**Comment by waiting-for-dev** [comment]
Hi @jfloff ,

try with:

```ruby
  devise :database_authenticatable,
         :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, :jwt_authenticatable, omniauth_providers: 
         [:facebook], jwt_revocation_strategy: JWTBlacklist
```

`devise` is a method which last argument is an options `Hash`. Maybe you see it clearer if you add the optional curly brackets:

```ruby
  devise :database_authenticatable,
         :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, :jwt_authenticatable, { omniauth_providers: 
         [:facebook], jwt_revocation_strategy: JWTBlacklist }
```

You see, you were adding to the hash something that is not a key/value pair, concretly `:jwt_authenticatable`, which is just a symbol. Therefore you got a syntax error.

**Comment by christophweegen** [comment]
@jfloff 

An essential rule to remember in that context is: You are only allowed to omit curly braces of a hash in a method call if it's the last argument. 

Since your last three method parameters include `omniauth_providers: [:facebook]` ( hash without curly braces ), `:jwt_authenticatable` ( a symbol ) and `jwt_revocation_strategy: JWTBlacklist` ( another hash without curly braces ) ruby complains since this isn't valid syntax, because there is a hash without curly braces that is not at the end. 

If you would have put `omniauth_providers: [:facebook]` in curly braces ( required since it's not the last argument ) it would be valid syntax, though it wouldn't satisfy the method signature in this case, since arguments aren't listed like @waiting-for-dev commented.

If you want to get to know all the little things about argument syntax in Ruby i can highly recommend https://www.manning.com/books/the-well-grounded-rubyist-third-edition. If you pre-buy the third edition ( which is still under writing ) you get a free ebook of the second edition, which helped me a lot regarding this topic :-) 

Happy programming!

**Comment by jfloff** [comment]
Oh man, I knew it was something simple! Thank you so . much for clear that up :)
