### ISSUE TITLE
[Question] Authenticate passing the email and password in a POST request

### ISSUE THREAD

**Issue by pepibumur** [waiting-for-dev/devise-jwt#111]
I'd like to use `devise-jwt` to authenticate users on a JSON API.

I'm currently using Devise with Rails admin to authenticate admins using the session strategy on the web. I've added `devise-jwt` and followed the steps on the README, including setting up the whitelist revocation strategy. According to the documentation, if the user authenticates using another strategy, `devise-jwt` will proxy the responses and add an `Authorization` header that the client can read and use to authenticate future requests.

The problem is that I would like to authenticate the users through an endopint in the JSON API. I was thinking about exposing a POST route `/api/auth/sign_in`, that reads two parameters, email and password, authenticates the user, and returns the JWT token in the JSON body.

I was wondering if there's any method that I can use from the controller to authenticate the user, get the JWT token generated and whitelisted, and return it back to the client. I've checked `devise-jwt` and `devise` documentation but I couldn't find anything.

Thank you very much for your help.

**Comment by waiting-for-dev** [comment]
> The problem is that I would like to authenticate the users through an endopint in the JSON API. I was thinking about exposing a POST route /api/auth/sign_in, that reads two parameters, email and password, authenticates the user, and returns the JWT token in the JSON body.

Doesn't it look like the standard `devise` (with `database_authenticatable` module) and `devise-jwt` workflow, but returning the JWT token in the response body instead that in the response headers? If so, it would be good if you could just stick with the token being in the headers.

> I was wondering if there's any method that I can use from the controller to authenticate the user, get the JWT token generated and whitelisted, and return it back to the client. I've checked devise-jwt and devise documentation but I couldn't find anything.

In order to authenticate users manually from the controller, you should use [`warden`](https://github.com/wardencommunity/warden) functions like `authenticate!`.  In order to get the token from the controller, surely https://github.com/waiting-for-dev/devise-jwt/issues/76 can help you.

**Comment by pepibumur** [comment]
Thanks @waiting-for-dev for the suggestion. It's working now 😛
