### ISSUE TITLE
Can this system work on an existing application

### ISSUE THREAD

**Issue by jujudellago** [waiting-for-dev/devise-jwt#127]
Hello

This is more of a general question than a specific problem with the gem.

I develop a 5.2 rails application, who has a web front end, uses devise, and handle a lot of data.

I would like now to develop an API for this same application, accessing the same data, the same elasticsearch indexes, and use the same user accounts.

At this point I am not sure if I'm going in the right direction, is this devise-jwt gem supposed to work exclusively in API mode ?  or can it work in an app who has both frontend and API ?   (or actually, is there anybody at all adding an API to an existing application, or I'm supposed to create a second application in API only mode ? )

thanks

**Comment by waiting-for-dev** [comment]
If your API is not going to be accessed from a different origin just keep using cookies for both HTML and JSON endpoints if possible.

But, surely, you need to access it from a different origin. In this case, sure, you can use both. Just be sure to understand [the session storage caveat](https://github.com/waiting-for-dev/devise-jwt#session-storage-caveat).

**Comment by jujudellago** [comment]
Thanks for the reply, took me a while to figure out how to create controllers and handle authorisation, but it's working nicely now

**Comment by augustosamame** [comment]
For me this is working fine for APIs and regular web calls.

But I don't really understand the session storage caveat. Does it mean that unauthenticated API calls will go through as authenticated even with wrong / missing token because there's another (different) user session present in web session?

However, when I change this line in Devise initializer:

from 

`config.skip_session_storage = [:http_auth]`

to

`config.skip_session_storage = [:http_auth, :params_auth]`

API (with JWT) keeps working fine, but web based login does not work anymore. Current user is nil on any subsequent call after login.

Any help is appreciated

**Comment by waiting-for-dev** [comment]
@augustosamame you got it right, it is as you say

**Comment by aruprakshit** [comment]
@augustosamame How did you manage it to fix? I am having exactly the same issue.
