### ISSUE TITLE
Not receiving Authorization in Header

### ISSUE THREAD

**Issue by waleedarshad** [waiting-for-dev/devise-jwt#13]
![header](https://cloud.githubusercontent.com/assets/5329697/26022991/27718a36-37cc-11e7-8855-84fa731dd305.png)

**Comment by waiting-for-dev** [comment]
I'll look at a way to manage it automatically, meanwhile see #10

**Comment by waiting-for-dev** [comment]
From version 0.3.0, a new setting `request_formats` is available in order to configure which formats should be taken into account for a given scope. For example, in this case it should have the following value:

```ruby
jwt.requests_formats = { user: [:json] }
```

See that [workaround proposed in issue #10](https://github.com/waiting-for-dev/devise-jwt/issues/10#issuecomment-297993345) has a subtle but important difference. There, both requests with no format or `json` format would dispatch/revoke tokens, while using the above configuration only fires the action on `json` format.

See the [Readme](https://github.com/waiting-for-dev/devise-jwt/issues/10#issuecomment-297993345) for more details.

**Comment by zoopyserg** [comment]
This should be in the Readme.
I just had the same issue.
