### ISSUE TITLE
Devise JWT and ActionCable

### ISSUE THREAD

**Issue by rohitbegani** [waiting-for-dev/devise-jwt#130]
I am using `devise-jwt` with `JwtBlacklist` as my revocation strategy. I am looking for a way to authenticate my actioncable connection by passing my JWT token in the initial `createConsumer`.

To do the above I mount my ActionCable with the path `/cable/:token` and I can then access the token in the `connection.rb` through the params.

It looks like `devise-jwt` does the authentication only through the header and I was wondering if there is a way I can manually authenticate the user, following which I can use the `current_user` in my `channel`

**Comment by waiting-for-dev** [comment]
`devise-jwt` (same as `devise` and `warden`) is a solution for http authentication, so it is not actually fitted for other kinds of protocols like web sockets. This means that you won't get much benefit using it. I mean, it is simpler if you manually craft a token using [`jwt`](https://github.com/jwt/ruby-jwt) and this way you won't be pulling all the code related to http authentication.

However, you can still use the library beneath `devise-jwt` [(`warden-jwt_auth`)](https://github.com/waiting-for-dev/warden-jwt_auth) to get some kind of support, even if it is still a solution with http in mind. You can manually [encode](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/user_encoder.rb) or [decode](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/user_decoder.rb) users and [revoke tokens](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/token_revoker.rb). But keep in mind you would be using a "more private" part of the library, because the worfkow in mind is, again, http authentication.

**Comment by rohitbegani** [comment]
@waiting-for-dev yeah that's a fair point. I am definitely playing around with the idea of creating another `jwt token` and use that to make `current_user` accessible in my `ActionCable` flow.

It seems like for normal devise authentication we can get the current user through the `env['warden'].user`. Is this possible even if we are using `devise-jwt` or is it not accessible because we can't send the authentication token?

**Comment by waiting-for-dev** [comment]
I'm not sure I'm getting your point. `env['warden'].user` can be accessed if the user has been set through a warden strategy. That includes `devise` strategies and `devise-jwt` strategy. So if you set the user through `devise-jwt` strategy (that's sending a valid JWT token in the headers) then it will be accessible. But you can't do that in the `ActionCable` flow.

**Comment by rohitbegani** [comment]
I asked about it for the `actioncable` flow because I saw a number of blog posts like [this](https://medium.com/@a.carreras.c/using-action-cable-for-private-messaging-presence-indicators-on-react-rails-app-526b3e34c14d) which say that `devise` can be used in the `connection.rb`.

<img width="716" alt="Screen Shot 2019-04-16 at 9 40 18 AM" src="https://user-images.githubusercontent.com/4975966/56214344-b4853600-602b-11e9-9374-4ef039800acb.png">

According to the above it seems like it should be possible to access the `user` from the `env['warden']`. I might be misunderstanding something over here though. I will look into it more and get back with my solution.

**Comment by rohitbegani** [comment]
I ended up generating a one time token which I generate during an initial route authentication on my application.

I share the token with the client side as part of the initial authentication and then in my `connection.rb` I refresh the token in my user record, essentially expiring the previous one. So my tokens are one time only and can only be acquired through the fetch request after the user has been authenticated.

I use [Rails 5 Secure Token](https://api.rubyonrails.org/classes/ActiveRecord/SecureToken/ClassMethods.html) for creating the authentication token.

**Comment by waiting-for-dev** [comment]
Thanks for sharing @rohitbegani

**Comment by Alagaesia93** [comment]
Any updates on this?

I don't want to use @rohitbegani solution to send secure token, I wish I could use
`env['warden'].user`
or 
`request.env['warden-jwt_auth.token']`

I have a Nuxt.js app which communicates with Rails api app. I want to introduce ActionCable so that background jobs (with Sidekiq) can push info to frontend. 

Thank you

**Comment by r4mbo7** [comment]
I didn't manage to manually decode a token with [UserDecoder](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/user_decoder.rb)...
```ruby
token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNTczMzkxMDUyLCJleHAiOjE1NzMzOTQ2NTIsImp0aSI6ImM2NDY1MzdhLThlMzktNGMwOC04OGE2LTFhYWYzZDk3Yjk2MiJ9.2d9401lYtETPQj6in92JIQ8gtHXM07VtUDxgk8VWPSE"
include Warden
decoder = JWTAuth::UserDecoder.new
decoder.call(token, "user", nil)
```
I have the following error
```
#<NoMethodError: undefined method `jwt_revoked?' for nil:NilClass>
```
What I am missing?
Thanks.

**Comment by waiting-for-dev** [comment]
Have you configured a revocation strategy for your scope?

**Comment by UICJohn** [comment]
> I didn't manage to manually decode a token with [UserDecoder](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/user_decoder.rb)...
> 
> ```ruby
> token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNTczMzkxMDUyLCJleHAiOjE1NzMzOTQ2NTIsImp0aSI6ImM2NDY1MzdhLThlMzktNGMwOC04OGE2LTFhYWYzZDk3Yjk2MiJ9.2d9401lYtETPQj6in92JIQ8gtHXM07VtUDxgk8VWPSE"
> include Warden
> decoder = JWTAuth::UserDecoder.new
> decoder.call(token, "user", nil)
> ```
> 
> I have the following error
> 
> ```
> #<NoMethodError: undefined method `jwt_revoked?' for nil:NilClass>
> ```
> 
> What I am missing?
> Thanks.

Hi there, you need to replace 'user' with :user. Then things is going to work

**Comment by KyleRAnderson** [comment]
Would [this solution](https://gist.github.com/PanosCodes/59c28bbb2a7f931d5fdc8a1c202e1da3#file-connection-rb) work and be considered valid? Found it on [this article](https://dev.to/panoscodes/get-the-current-user-in-actioncable-4d9b).

**Comment by min-verse** [comment]
> Would [this solution](https://gist.github.com/PanosCodes/59c28bbb2a7f931d5fdc8a1c202e1da3#file-connection-rb) work and be considered valid? Found it on [this article](https://dev.to/panoscodes/get-the-current-user-in-actioncable-4d9b).

Maybe I'm two years and one pandemic too late, but were you able to confirm this? Working on a Rails 6 API with devise-jwt for auth and a separate React frontend

**Comment by KyleRAnderson** [comment]
I ended up switching to cookie based authentication since it seemed to match my primarily browser use case better @min-verse, so I didn't get a chance to try out that solution.
