### ISSUE TITLE
Sign in Failed

### ISSUE THREAD

**Issue by alfie-max** [waiting-for-dev/devise-jwt#17]
Rails 5.1.1
Ruby 2.4.1

Tested on both devise-jwt  0.1.1 and 0.3.0

Tried to signup a user, got a success response with the `jti` in response

Next tried to sign_in by passing the generated jti in the authorization header.
But i get a response of `Failed to Login`

I'm attaching the postman images of the same.

![screen shot 2017-06-20 at 14 40 02](https://user-images.githubusercontent.com/8247590/27325524-66600250-55c6-11e7-9df0-095d6af78564.png)

![screen shot 2017-06-20 at 14 40 12](https://user-images.githubusercontent.com/8247590/27325529-6bae59a0-55c6-11e7-9475-d9d590005f20.png)

**Comment by waiting-for-dev** [comment]
@alfie-max what you have to provide in order to authenticate is not the `jti` claim but the whole token you get in the `Authorization` response header after your sign up.

`jti` is not the token, it is just a claim that uniquely identifies it and that, in this library, is used for token revocation purposes. In fact, there is no need to return it in the response.

**Comment by alfie-max** [comment]
Lol, i though i was doing it wrong. can you advice on how the right way to authenticate is.

**Comment by alfie-max** [comment]
Got it, i didn't check the headers in the response.
Going to close this now.
