### ISSUE TITLE
Token dispatch for GraphQL Ruby login

### ISSUE THREAD

**Issue by sdeluc1** [waiting-for-dev/devise-jwt#181]
I have a Rails API using `graphql-ruby` (https://github.com/rmosolgo/graphql-ruby) and have recently started to implement authentication with `devise-jwt`. I'd like to be able to dispatch a token when login happens through a GraphQL mutation, but I'm running into some issues because the endpoint for all GraphQL requests is `POST /graphql`, which I added to the `dispatch_requests` array in the `devise-jwt` config. I'm using the `AllowlistedJwt` strategy, so every GraphQL request after initial login is causing a new token to be created and added to the `allowlisted_jwts` table.

I noticed that `warden-jwt_auth` is running the `after_set_user` hook for all event types, mainly `:set_user` and `:authentication`. If I update the code in `lib/warden/jwt_auth/hooks.rb` to only run hooks for `:set_user` events, my issue is resolved:
```
Warden::Manager.after_set_user only: :set_user do |user, auth, opts|
  Warden::JWTAuth::Hooks.after_set_user(user, auth, opts)
end
```

- Is there a way to handle this use case with the existing configuration options?
- If not, would it make sense to add some configuration to dictate which events this hook should run for?

Relevant versions:
`graphql-ruby v1.10.10`
`rails v5.1.7`
`devise-jwt v0.7.0`
`warden-jwt_auth v0.4.0`

**Comment by waiting-for-dev** [comment]
> Is there a way to handle this use case with the existing configuration options?

I don't think so.

TBH I wasn't aware of this configuration on `:after_set_user` hook. I guess that changing it is working for you because you have your session enabled, right? But then you should be aware of the [token storage caveat](https://github.com/waiting-for-dev/devise-jwt#session-storage-caveat).

Not related, but if you're not using devise at all, you could make it work just with [`warden-jwt_auth`](https://github.com/waiting-for-dev/warden-jwt_auth) library, which is the engine under 'devise-jwt`.

**Comment by waiting-for-dev** [comment]
Closing, feel free to add more comments if needed
