### ISSUE TITLE
Question: two-factor

### ISSUE THREAD

**Issue by jvelez1** [waiting-for-dev/devise-jwt#209]
Hello, 

I've implemented devise-jwt for authentication API, and now I need to integrate OTP (two-factor), not sure if devise-jwt support something like that, or if you guys recommend any other gem that works with this. 

Thanks, and sorry for the inconvenience.

**Comment by waiting-for-dev** [comment]
Hi @jvelez1 ,

two-factor belongs to the first authentication domain, the one that you do, for instance, with `database_authenticatable` devise strategy. `devise-jwt` always relies on that first step having been executed (it will never return a token just because). You can check [devise's wiki page on extensions](https://github.com/heartcombo/devise/wiki/Extensions). I know they're at least two of them handling 2FA, but I have no experience with them.
