### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by Bdoom** [waiting-for-dev/devise-jwt#214]
Can you show me an example of an http request to /users/sign_in.json? and what I need to be passing into it?

**Comment by Bdoom** [comment]
![image](https://user-images.githubusercontent.com/1284431/119912749-05192e00-bf2a-11eb-82b1-783d667b0214.png)
This is what I'm doing, and the result...

**Comment by waiting-for-dev** [comment]
Hi @Bdoom. You can look at the [rails application on the test suite](https://github.com/waiting-for-dev/devise-jwt/tree/master/spec/fixtures/rails_app) for examples. Also, following the Readme closely should be enough to make it work. Otherwise, please, open an issue with your problem filling in the bug template that is prompted.
