### ISSUE TITLE
Unable to switch to JWT authentication even after following instructions

### ISSUE THREAD

**Issue by rastogiachyut** [waiting-for-dev/devise-jwt#29]
I have the following in my user model, but still when I login the authentication happens using sessions.

```
  devise :database_authenticatable, :jwt_authenticatable, :registerable, :confirmable,
         :rememberable, :validatable, :recoverable, :lockable, :trackable,
         :timeoutable, timeout_in: 7.days, jwt_revocation_strategy: Devise::JWT::RevocationStrategies::Null
```

**Comment by waiting-for-dev** [comment]
This gem doesn't infer in the session, so you have to disable it on your own.

**Comment by rastogiachyut** [comment]
Thanks, that answers my question, but can we have this explicitly mentioned somewhere. Or can we have a link to a tutorial in the readme?

**Comment by waiting-for-dev** [comment]
It is somehow unrelated, because one could use this gem for API authentication and sessions for web authentication. Also, an authentication library is not responsible of disabling sessions, because sessions can be used for more things that authentication. But I agree that a good tutorial on how to use devise in APIs is missing.
