### ISSUE TITLE
Remove default JWT payload attributes

### ISSUE THREAD

**Issue by cilim** [waiting-for-dev/devise-jwt#31]
I need to create an API that's going to use JWT authentication, but the jwt tokens should never expire.

Currently, after a successful `sign_in` or `sign_up`, the response contains the `Authorization` header that has the jwt, and after decoding it, the payload contains the `exp` attribute, which will cause the client token to become useless after a while.

How can I reject the `exp` attribute from the JWT payload?

I tried it like so in my user model:

```ruby
def jwt_payload
  super.except!('exp')
end
```

and like so:

```ruby
def jwt_payload
  {
    jti: jti
  }
end
```
I only need the `jti` inside the payload.

**Comment by waiting-for-dev** [comment]
The result of `jwt_payload` method in the user model is merged into [some defaults generated in `warden-jwt_auth` dependency](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/token_encoder.rb#L27). So currently there is no clean way of removing the `exp` claim.

I thought some time ago about adding this possibility, but, at least for now, I ruled it out for security concerns. This gem is meant to be used as a cookie substitution mechanism when this solution is not possible because cross-origin requests or whatever. As cookies, I find it a good practice to force the user to define an expiration time (cookies can neither live forever).

If you are in an scenario where users will never be signed out, you will be better off with a solution working with refresh tokens, like OAuth 2 (check [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) for rails).

Of course, you can cheat the system and define an expiration time for 2200, that's up to you ;)

**Comment by cilim** [comment]
Thank you for your quick reply :)

**Comment by zachGl** [comment]
Hi, is there a way to implement the 'remember me' functionality with devise-jwt?

**Comment by waiting-for-dev** [comment]
If the client provides a valid token, the server will "remember" it.

**Comment by zachGl** [comment]
Thank you for the quick response.

Can I set the expired date per user?
Alternatively can I check if an expired token is valid and return a new one?

**Comment by waiting-for-dev** [comment]
> Can I set the expired date per user?

https://github.com/waiting-for-dev/devise-jwt/issues/109

> Alternatively can I check if an expired token is valid and return a new one?

https://github.com/waiting-for-dev/devise-jwt/issues/114
