### ISSUE TITLE
Invalid token on sessions#destroy

### ISSUE THREAD

**Issue by Reedian** [waiting-for-dev/devise-jwt#43]
I have encountered a bug while writing request tests. I wanted to make sure that `devise-jwt` handles corner cases such as the invalid format of JWT token or invalid JWT token but unfortunately it's not.

For invalid format it returns a `JWT::DecodeError` with 500 status code. 
For invalid JWT it returns a `JWT::VerificationError` with 500 status code. 

I wanted somehow to find a workaround by implementing `ExceptionHandler` with `rescure_from` for these two errors. 
```
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from JWT::DecodeError, with: :unauthorized_request
    rescue_from JWT::VerificationError, with: :unauthorized_request
  end

  private

  def unauthorized_request(e)
    render json: { message: e.message }, status: :unauthorized
  end
end
```
I have added it to my SessionController and overridden destroy action (I had to add `verify_signed_out_user` in order to override destroy method):
```
module Api
  module V1
    class SessionsController < Devise::SessionsController
      skip_before_action :verify_signed_out_user
      include ExceptionHandler

      def destroy
        binding.pry
      end
    end
  end
end
```
At this moment every request triggers my binding.pry but then it seems that gem does own logic on top it, so I'm not able to rescue from these errors. 

EDIT:
Okay, I make a workaround by writing custom middleware which catches those errors.

**Comment by waiting-for-dev** [comment]
Hi @Reedian ,

I'm not sure about your issue. `devise-jwt` doesn't rescue from those exceptions, so you should be able to do it yourself. I think it is ok that the gem doesn't do it itself, because it is up to each application to decide what to do (a 500 html response? a 500 json response?)

**Comment by Reedian** [comment]
@waiting-for-dev as all we know 500 status code means server-side issue and I don't think that it is normal behaviour for any gem to throw an error which must be handled later manually. 

With `devise` example it comes to a pretty easy setup of gem which covers most of the corner cases. So what I expect from adding `devise-jwt` to my project is to all of the corner cases be still covered. 

I agree with you that is up to the developer how he wants to handle certain situations. Although these cases are already covered in case of user authentication. Token revocation during the devise session destroy is a pretty similar to user authentication. Why isn't it resolved by the same way then? Or at least to mention it in the documentation.

**Comment by waiting-for-dev** [comment]
> @waiting-for-dev as all we know 500 status code means server-side issue and I don't think that it is normal behaviour for any gem to throw an error which must be handled later manually.

A gem (or any other kind of library) is meant to be used by a programmer and not by the end user. The responsibility of a library is to return a meaningful error when something happens. It is the application which should transform those errors in something digestible by an end user. Rails, as (at least) the web interface of the application, has a sensible default to render a 500 response when an exception is not handled.

> With devise example it comes to a pretty easy setup of gem which covers most of the corner cases. So what I expect from adding devise-jwt to my project is to all of the corner cases be still covered.
>
> I agree with you that is up to the developer how he wants to handle certain situations. Although these cases are already covered in case of user authentication. Token revocation during the devise session destroy is a pretty similar to user authentication. Why isn't it resolved by the same way then? Or maybe at least to mention it in the documentation.

So what would you expect to happen when an invalid token is given? The only reasonable thing I can think is to silently unauthenticate the user. But the problem with this is that it would hide an error in the application. If the application is sending invalid tokens, the best is to have an error raised so that it is logged and the programmer can detect it inspecting the logs or using any monitoring solution. If, instead, it is a malicious user who is trying to send invalid tokens, there is no harm in showing him a 500 page instead of adding a bunch of defensive code (which in turn increases the options of introducing undetected attack vectors).

**Comment by Reedian** [comment]
I haven't thought about attack vectors. You are right, it should stay as it is.

I think it is a good idea to place somewhere in documentation information about handling this kind of situation or just inform how gem behaves with invalid tokens. What do you think?

**Comment by waiting-for-dev** [comment]
I added a [commit](https://github.com/waiting-for-dev/warden-jwt_auth/commit/2a005b7e13035c648914e647ac831c48d2aac661) in underlying gem `warden-jwt_auth` with documentation that points in the direction where all possible exceptions raised on decoding can be checked.

So I'm going to close it. Feel free to add more comments if you have any doubt or suggestion. Thanks for reporting.
