### ISSUE TITLE
Invalidation Advice (OR) pruning the blacklists table

### ISSUE THREAD

**Issue by subvertallchris** [waiting-for-dev/devise-jwt#44]
Excuse me for posting here what would better go on Stack Overflow, but I fear I won't get enough knowledgable eyes on it there.

I'm currently using the `self` revocation strategy. With this strategy, a user signed into multiple devices is signed out from all of them when they request signout from any individual device. (Signing out from web will disconnect them on mobile, etc,...) This makes sense, given the definition of the `self` strategy as I understand it. I assume that `blacklist` strategy might be more appropriate for my use case, but at that point, what exists (if anything) to keep that table from growing forever? Schedule a job to purge rows that have already expired, since they'd be no good anyway? Anything better?

Appreciate your advice.

**Comment by subvertallchris** [comment]
Thanks for the quick response. Have you considered using Redis with EXPIRE values to automatically prune?

**Comment by waiting-for-dev** [comment]
Yes @subvertallchris , I agree that would be a good fit. However, I don't want to add it in the gem distribution because I only want to have rails specific strategies that can be used out of the box and that can serve as examples to implement other strategies very easily as [custom strategies](https://github.com/waiting-for-dev/devise-jwt#custom-strategies)

As you say, I'm neither a fan of adding tech dependencies. Probably I would consider using Redis if I was already using it, otherse I would go with the Rails way and change later if the need arises.

**Comment by subvertallchris** [comment]
Makes total sense. I'll probably throw one together using Redis as a custom strategy, will ping you if it seems worth sharing. Thanks for your help.
