### ISSUE TITLE
JTI Strategy for multiple clients (multiple web laptops, phones etc)

### ISSUE THREAD

**Issue by redroot** [waiting-for-dev/devise-jwt#48]
Just wondering what your thoughts on using a JTI strategy for users who can have access from multiple clients devices. For example:

1) User is signed in on laptop at home in Chrome via web client, web client stores JWT token there
2) User is signed in on laptop at work in Safari via web client, web client stores JWT Token in localStorage there
3) User is signed in on their mobile phone via a native app, app stores JWT token in storage on the phone.

Would you have a jti for each uniquely identifiable client (some function of device and ip Im guessing) per user record in the database?

**Comment by waiting-for-dev** [comment]
Hi @redroot ,

I think this makes sense, mainly when the use case is a user signed in from more than one laptop. If the idea is to support multiple devices (like a smartphone app, where a user usually never signs out) I think it is better to use a solution with refresh tokens, for example through some OAuth implementation.

But, for that to work out of the box, [warden-jwt_auth](https://github.com/waiting-for-dev/warden-jwt_auth) should be able to take something from the client (surely an HTTP request header) and add it to the JWT payload. Then, it would be quite easy to implement a revocation strategy from `devise-jwt` comparing both the `jti` and that client identifier.

I'll try to implement it when I find the time. Meanwhile it should be quite easy to implement a custom revocation strategy and also manually maintain the client identifier in another database table or somewhere.

**Comment by redroot** [comment]
@waiting-for-dev thanks for replying, if I end up going that route i'll look into a PR myself 👍

**Comment by pablocrivella** [comment]
I implemented this as `Device Whitelist` strategy:

```ruby
module Devise
  module Jwt
    module RevocationStrategies
      module Devices
        extend ActiveSupport::Concern

        included do
          attribute :current_device_id, :string, default: -> { SecureRandom.uuid }
        end

        def self.jwt_revoked?(payload, account)
          !account.devices.exists?(id: payload['jti'])
        end

        def self.revoke_jwt(payload, account)
          account.devices.find_by(id: payload['jti']).destroy
        end

        def jwt_payload
          { 'jti' => find_or_create_device.id }
        end

        private

        def find_or_create_device
          devices.find_or_create_by(id: current_device_id)
        end
      end
    end
  end
end
```

I requires to create a `devices` table where the id is a `uuid`.

NOTE: I delete all the devices after a password reset to revoke all existing tokens.

Do you guys think this is an strategy that could be included in the gem?

**Comment by waiting-for-dev** [comment]
Hi @pablocrivella , thanks for your valuable feedback.

The only problem I see is that, if I'm not wrong, it doesn't allow to differentiate one client (or device) from another one, so a user could be able to use a token issued to client A from client B. Surely it doesn't suppose a problem in a lot of cases, and if it is so in your case you are perfectly fine using your revocation strategy.

Currently I'm modifying the underlying `warden-jwt_auth` gem so that it provides a way to encode information taken from rack env into the JWT payload. This way it will be possible to persist a client identifier information as a claim. This, together with a way to compare incoming tokens with incoming request envs will allow to validate whether a token is being used by the expected client.

**Comment by pablocrivella** [comment]
Thanks for your reply! @waiting-for-dev looking forward to check your implementation :)

**Comment by waiting-for-dev** [comment]
Hi there,

I just released `warden-jwt_auth 0.3.0` with some changes specifics to address the issue discussed here.

First of all, the [client validation will be something done automatically](https://github.com/waiting-for-dev/warden-jwt_auth#requesting-client-validation) (and independent of any revocation strategy). A new `config.aud_header` configuration parameter is provided, which value is the request header name which content will be copied to the `aud` claim in the JWT. On each authorization, the value in the header and the value in the JWT are matched.

This leaves us with a revocation strategy with less responsibilities. In fact, the only that we need is a kind of whitelist revocation strategy which additionally could store the `aud` claim just to prevent having more than one token valid at a time per single client.

@pablocrivella , your revocation strategy is almost the perfect fit for this. So before implementing it myself I would like to ask you whether you would like to do it yourself. If you need some help, I would happily assist you with a code review or direct comments. If you prefer not or you don't have the time, no worries, I would do it myself.

Some changes I think should be implemented are:

- Change the `device` nomenclature for a more generic `jwt` (as I said, the device validation happens outside the strategy), and `user` instead of `account` to be consistent with other strategies.

- Instead of abusing of the `jwt_payload` method to create related records, use the new hook method I just introduced in `warden-jwt_auth 0.3.0` called `on_jwt_dispatch(token, payload)`.

- Store the `aud` claim along the `jti` to be sure that only one valid token exists at a time for each client.

If you are interested in taking it, we can discuss it with more detail.

**Comment by pablocrivella** [comment]
Hey @waiting-for-dev! Great news! I would really like to help you with this PR. I think I can find time to do it soon, I'll apply your suggestions and of course improvements will be very much welcome when you are doing the review! :)

**Comment by waiting-for-dev** [comment]
Happy to hear that @pablocrivella :) Looking forward for your contribution :)

**Comment by pablocrivella** [comment]
@waiting-for-dev What value would you put on the JWT_AUD header to identify a client?

**Comment by waiting-for-dev** [comment]
Say you have your app running in device A and device B for the same user, but you just want to authorize some client side feature in device A. Then, checking `JWT_AUD` header allows you to check in device B that incoming token was not issued for device A (as long as the response can't be manipulated as in a web app). I recognize that it is not a very common scenario, but I want to follow "secure by default" principle here.

**Comment by pablocrivella** [comment]
Yeah i got that but i meant more the actual value. For example for a browser, what value cuould i put on the JWT_AUD to identify it uniquely.
Like a browser-uuid i guess? Same would be for smartphones, the uuid of the device.
Does it make sense?

**Comment by waiting-for-dev** [comment]
To be honest I didn't think about the actual value, but these are good options :)

**Comment by ricardopinto08** [comment]
Maybe you could store in aud header the IP of your device or an ID generated by the frontend.
I implemented a solution for allow request only for each user, for example if i logged in as User 1 I only can request my own data, that verification is done overwriting the authenticate_user! method in application_controller.rb decoding the token and looking if the decoded user id is the same that client is requesting.
Salu2
