### ISSUE TITLE
Use `where` instead of `find` for `self.jwt_find_for_authentication`

### ISSUE THREAD

**Issue by carsomyr** [waiting-for-dev/devise-jwt#52]
I noticed that in the event the JWT's user is deleted, the `find` method in [`jwt_authenticatable.rb`](https://github.com/waiting-for-dev/devise-jwt/blob/master/lib/devise/jwt/models/jwt_authenticatable.rb#L19-L21) is causing my REST API to give 404 Not Found errors (bubbled upwards from an `ActiveRecord::RecordNotFound` exception). Would a `where(id: sub).first` scope be more appropriate? I'm not sure how you would integrate this with JWT subject fields.

Anyhow, I believe that a change is necessary here because Devise's own `find_for_database_authentication` doesn't throw exceptions and returns `nil` for not-found emails.

**Comment by waiting-for-dev** [comment]
Hi @carsomyr ,

for now I prefer to be explicit and raise an exception instead of setting a `nil` user. I think it is safer. At the most, a custom exception could be raised but I don't feel like adding more complexity to the code just for such a corner case scenario (a deleted user trying to access again). I think one source of confusion in your code is having something that rescues any `ActiveRecord::NotFound` to render a 404 page, when surely it is not the desired behavior in a lot of situations and hides an error from the logs.

**Comment by carsomyr** [comment]
@waiting-for-dev FYI, if you trace Devise's `find_for_database_authentication` (assuming ActiveRecord as a backend), it ends up with a [`first` call on ActiveRecord](https://github.com/ianwhite/orm_adapter/blob/master/lib/orm_adapter/adapters/active_record.rb), which means that `nil` is preferred way to signal that a user isn't being found by email. In the case of JWT, that's the subject field. I don't think that Devise is configured to catch `ActiveRecord::NotFound` exceptions that arise from `find_for_*` methods.

**Comment by waiting-for-dev** [comment]
> FYI, if you trace Devise's find_for_database_authentication (assuming ActiveRecord as a backend), it ends up with a first call on ActiveRecord, which means that nil is the preferred way to signal that a user isn't being found by email

Hmm, this is interesting. I still find I prefer to be explicit, but I will reopen the issue to give it a second thought as soon as possible.

>  I don't think that Devise is configured to catch ActiveRecord::NotFound exceptions that arise from find_for_* methods.

I'm not saying it comes from devise. Maybe the application itself, I don't know.

**Comment by carsomyr** [comment]
@waiting-for-dev TL;DR: I'm no Devise expert, but I believe that `nil` detection when "finding" a user is convention and will eventually be propagated into 402 Unauthorized (from Devise itself) instead of 404 Not Found (caught by whatever low-level Rack middleware is available).

**Comment by waiting-for-dev** [comment]
You are right, [devise unauthorizes if user is nil](https://github.com/plataformatec/devise/blob/master/lib/devise/strategies/database_authenticatable.rb#L18).

I will though have to propagate the change to `warden-jwt_auth`, because the strategy used is there. `devise-jwt` will return `nil` and `warden-jwt_auth` will unauthorize in such a case. In fact, right now `warden-jwt_auth` is authenticating a `nil` user.

Thanks for pointing that out. I'll implement it and report here.

**Comment by waiting-for-dev** [comment]
Fixed.

Now, `warden-jwt_auth 0.2.0` unauthorizes when the user fecthed from the repository is nil. And, here, `devise-jwt 0.4.3` depends on `warden-jwt_auth 0.2.0` and returns `nil` instead of raising when a user is not found in the database.

Thanks for reporting

**Comment by carsomyr** [comment]
@waiting-for-dev Thanks!
