### ISSUE TITLE
Are tokens revoked after a password change?

### ISSUE THREAD

**Issue by pablocrivella** [waiting-for-dev/devise-jwt#53]
Is this something this gem should handle as a part of the revocation strategy or is it something that needs to be done on the devise side?

PS. Pretty cool gem btw!

**Comment by waiting-for-dev** [comment]
Hi @pablocrivella ,

why do you need to revoke a token after the password changes? Do you want your users to be signed out when they change their password?

**Comment by pablocrivella** [comment]
Since i have to support signing in from multiple devices I want to force all of them to log in again

**Comment by waiting-for-dev** [comment]
[As far as I know](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password), there is no way in devise to differentiate (through the registerable module) a password update from any other user fields update, and this gem doesn't want to monkey patch devise controllers, so for now you should manage it manually through [`warden-jwt_auth`](https://github.com/waiting-for-dev/warden-jwt_auth) API (look at [`TokenRevoker`](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/token_revoker.rb)).

In #48 it will be implemented a revocation strategy for multiple clients. Maybe there I'll see a way to implement an  `after_update` callback revoking all associated tokens. I'll study it and report.

**Comment by waiting-for-dev** [comment]
With #58 merged, now it is very easy to just add an `after_update` callback to a model using the [whitelist strategy with the `aud` claim](https://github.com/waiting-for-dev/devise-jwt#whitelist). I prefer not to add it out of the box because it may work different in different cases and, again, it is very easy to implement for the scenarios that need it.

**Comment by waiting-for-dev** [comment]
Anyway, anybody wanting support on how to implement it, feel free to add comments here.

**Comment by stefanrendevski** [comment]
Hi @waiting-for-dev. I am using the whitelist revocation strategy to allow a user to sign in from multiple devices. However, on credential change, I need to be able to revoke all issued tokens for that user.

Is my understanding correct that in order to achieve this, I need to delete all WhitelistedJwt tokens associated with the user? Is there anything else that needs to be done?

**Comment by pablocrivella** [comment]
@stefanrendevski deleting that specific user `whitelisted_jwts` should be suficient, ie:

```ruby
class PasswordsController < Devise::PasswordsController
  def update
    super do |user|
      user.whitelisted_jwts.destroy_all if user.errors.empty?
    end
  end
end
```
