### ISSUE TITLE
JWT acronym inflection not supported

### ISSUE THREAD

**Issue by pablocrivella** [waiting-for-dev/devise-jwt#57]
Adding `JWT` acronym to the inflector `config/inflections.rb`

```ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym 'JWT'
end
```

Generates the following exception:

NameError: uninitialized constant Devise::Models::JWTAuthenticatable

**Comment by waiting-for-dev** [comment]
Thanks for reporting @pablocrivella .

You are right in that adding `JWT` acronym makes the application crash because this gem. But the reason for that is that `devise` is [using inflection rules to load modules](https://github.com/plataformatec/devise/blob/master/lib/devise/models.rb#L88). So, when `JWT` acronym is not set, adding `:jwt_authenticatable` to the model results in trying to load `JwtAuthenticatable`module (it exists), while when `JWT` is an acronym it tries with `JWTAuthenticatable` (it doesn't exist).

We could add ourselves the `JWT` acronym in the railtie, and then rename `JwtAuthenticatable` module to `JWTAuthenticatable`. This will make the inflection and the gem both work.

On the other hand, rails itself is [closed to patches adding new inflection rules](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html):

> The Rails core team has stated patches for the inflections library will not be accepted in order to avoid breaking legacy applications which may be relying on errant inflections.

So, should we add custom application rules to our railtie, we would be doing the same and, therefore, adding the possibility to break applications (which, in my view, shows that the oberused inflections abstraction is broken). Furthermore, adding acronyms only in English could result in inconsistencies for other languages.

So, I'm afraid it's better doing nothing here and if you need to treat JWT as an acronym somewhere else you should do it manually.

**Comment by pablocrivella** [comment]
Thanks for the detailed explanation @waiting-for-dev 

I agree with what you say, feel free to close this issue :)
