### ISSUE TITLE
sign out not working

### ISSUE THREAD

**Issue by czsie-developer** [waiting-for-dev/devise-jwt#83]
the token is still valid after sign out

**Comment by czsie-developer** [comment]
i am using jti revocation strategy

**Comment by waiting-for-dev** [comment]
Is it still valid after you closed #84 ?

**Comment by czsie-developer** [comment]
i was using an older version of the gem, when updated the revocation works fine only for the session destroy path, configuring revocation path in devise initializer has no effect

**Comment by waiting-for-dev** [comment]
So, if sign out is working while another path isn't, which issue should be still open? This one or #84?

Please, fill in the following bug report in the appropriate issue and I'll reopen it:

## Expected behavior

## Actual behavior

## Steps to Reproduce the Problem

1.
2.
3.

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use
- Version of `rails` in use
- Output of `Devise::JWT.config`
- Output of `Warden::JWTAuth.config`
- Output of `Devise.mappings`
- If your issue is related with not getting a JWT from the server:
  - Involved request path, method and request headers
  - Response headers for that request
- If your issue is related with not being able to revoke a JWT:
  - Involved request path, method and request headers
