### ISSUE TITLE
Is there a method for just checking the validity of the token, like token.valid?

### ISSUE THREAD

**Issue by alliesground** [waiting-for-dev/devise-jwt#90]
Hi,
Just wanted to know which method checks the validity of the token and if I can reuse it, or do we have to implement it ourselves, something like token.valid?

Thanks for the gem.

**Comment by waiting-for-dev** [comment]
For that you have to rely on underneath  `warden-jwt_auth`. You can call `Warden::JWTAuth::UserDecoder.new.call(token, scope, aud)`. If the token is valid it will return the encoded user. Otherwise, some kind of `JWT::DecodeError` will be raised.

Note: `scope` is the devise scope, like `:user`. `aud` is the [encoded aud claim](https://github.com/waiting-for-dev/devise-jwt#aud_header) (`nil` if not configured).

**Comment by alliesground** [comment]
I wanted to check the validity of the token, to check whether the token has expired.

But with this approach for every request to the REST api I'm making additional request for checking the validity of the token, which the REST api request does anyways right?

I'm not sure if it's possible for the server to let the client know when the token expires.

**Comment by waiting-for-dev** [comment]
You can read the token contents (its payload). It is just base64 encoded, but not encrypted. You can check it online in the debugger at https://jwt.io/. Sure there are JS libraries to read it. The expiration time is encoded in the `exp` claim.

**Comment by alliesground** [comment]
Got it Marc. I'll decode it and set the timer in client side, so that users will be redirected to login page after the timers from the token expires.

Thanks for your help. Cheers.
