### ISSUE TITLE
Can I accept GET param along header (Authorization: Bearer ...)

### ISSUE THREAD

**Issue by dachinat** [waiting-for-dev/devise-jwt#94]
Hello. I have been working with `devise-jwt` and client async API and it has been great so far.

Sometimes, however, I'm in a situation where I can't set HTTP header (Authorization: Bearer ...).

For example, currently I fetch an incoming e-mail message with async + devise-jwt, and I need to replace `src="cid:xxx"` with `src="attachment/yyy"` for attachments to be rendered (There has to be a route `attachment/:id` that will serve a file). Having that said, I need to get authorized with Devise with something like `attachment/yyy?authorization=zzz`.

Is it possible to use `devise-jwt` in such situation? May I ask for your recommendations? Thanks.

**Comment by waiting-for-dev** [comment]
No, out of the box `devise-jwt` takes the token from the headers and not from the params. It is also a decision design, because I think it is more probable to have a secure issue if we accept tokens in the params, because params are usually stored in the browser history (of course, it is always possible to record the headers history, I only talk about probabilities). 

I think for that scenario (authenticating from an email) I would decouple from devise. I would generate another JWT token (using [ruby-jwt](https://github.com/jwt/ruby-jwt), which is already a `devise-jwt` dependency) and I would use some kind of server side storage to invalidate it once it is used. As the user email credentials already authenticate him, maybe there is no need to authenticate through the token. It is enough to trust it. But it is just a quick thought.

**Comment by dachinat** [comment]
@waiting-for-dev Thanks for your response, really appreciate that. Will take your recommendations into account.

**Comment by dachinat** [comment]
By the way, if anyone will still decide to have token in query params, you could use a middleware

**middlewares/jwt_param.rb**
```
class JWTParam
  def initialize app
    @app = app
  end

  def call env
    request = Rack::Request.new(env)
    env["HTTP_AUTHORIZATION"] = "Bearer #{request.params["authorization"]}"
    @status, @headers, @response = @app.call(env)
    @app.call(env)
    [@status, @headers, @response]
  end
end
```

**application.rb**
```
    #...
    config.middleware.use JWTParam
```
