### ISSUE TITLE
Cannot sign in user with Devise::JWT::TestHelpers.auth_headers in integration test

### ISSUE THREAD

**Issue by RainThinks** [waiting-for-dev/devise-jwt#99]
Rails 5.2 (api only) + devise-jwt 0.5.7

## Expected behavior
should pass authenticate_user!

## Actual behavior
Authorization header was set correctly, but can't pass authenticate_user!. Meanwhile, the whitelisted_jwts table was empty.

## Steps to Reproduce the Problem

1. devise & devise-jwt config, use Whitelist strategy
```
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Whitelist
  devise :database_authenticatable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self
         
end
```

2. Spec
```
require 'rails_helper'
require 'devise/jwt/test_helpers'

RSpec.describe "GET INFO", type: :request do
  describe "GET /info" do
    it "cannot pass the authentication" do
      user = User.create(email: 'test@example.com', password: 'password')
      headers = { 'Accept' => 'application/json', 'Content-Type' => 'application/json' }
      auth_headers = Devise::JWT::TestHelpers.auth_headers(headers, user)
      
      get "/admin/coaches/1/courses/overview", headers: auth_headers # before_action authenticate_user!
      
      # All assertion passed.
      expect(user.valid?).to be(true)
      expect(user.whitelisted_jwts).to be_empty
      expect(response.request.headers['Authorization']).to eq(auth_headers['Authorization'])
     # this assertion passed, but expected to fail
      expect(response).to have_http_status(401)
    end
  end
end
```

**Comment by waiting-for-dev** [comment]
Hi @RainThinks ,

are your sure your 401 unauthorization is due to `devise-jwt`? Which response body are you getting?

If so, could you check that the user is indeed being created? Does it have an id? Or, otherwise, use `create!` insted of `create`. Being `valid?` does not guarantee that it has been created.

Also, could you please paste the rest of debugging information mentioned in the bug reporting template?

Thanks

**Comment by waiting-for-dev** [comment]
Closing because the lack of feedback. Please, feel free to add more comments if this is still an issue for you.

**Comment by RainThinks** [comment]
I read through the implementation. Calling  `Devise::JWT::TestHelpers.auth_headers(headers, user) ` would only generate a new token, but the jti is not added to whitelist_jwts table. When service authenticate the request with the token, the Whitelist RevocationStrategies would treat it as revoked, since no matched records found in database. That would leads the authentication failed.

**Comment by jovanmaric** [comment]
I'm having the same issue when trying to authenticate for a Devise::RegistrationsController spec. The user exists (checked with User.all) and the token gets generated properly. However by calling current_user or checking the "user.whitelisted_jwts" it returns an empty array. Therefore invalidating the authentication. 

Is there an eta on when this will be fixed?

**Comment by waiting-for-dev** [comment]
Please try whether branch `testing_hooks` fixes your issue.

**Comment by jovanmaric** [comment]
Sorry for the late response. It seems the whitelisted_jwts are generated correctly, however I can't still seem to authenticate in my Devise::RegistrationsController spec. The error is with the following `authenticate_scope!` method which fails:

```
class RegistrationsController < Devise::RegistrationsController
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy]

  # GET /resource/edit
  def edit
    # render :edit

    no_content
  end

  protected

    def authenticate_scope!
     # NOTE: This method fails 
      send(:"authenticate_#{resource_name}!", force: true)
      self.resource = send(:"current_#{resource_name}")
    end
end
```
And the spec:
```
RSpec.describe Api::Users::RegistrationsController, type: :request do
  let(:user) { create(:user) }

  describe 'GET #edit' do
    context 'when successful' do
      before do
        get edit_user_registration_path, headers: auth_headers(user)
      end
  
      it 'returns nothing' do
        expect(response.body).to eq('')
      end
  
      it 'returns status 204' do
        expect(response.status).to eq(204)
      end
    end
  
    context 'when unsuccessful' do
      before do
        get edit_user_registration_path
      end
  
      it 'returns http status 401' do
        expect(response.status).to eq(401)
      end
  
      it 'has a correct schema' do
        expect(response).to match_json_schema('status')
      end
    end
  end
end
```

I'm not sure, but can this by any chance be related?

**Comment by waiting-for-dev** [comment]
Original issue has been fixed in master and released in version `0.5.8`.

Your new issue doesn't seem related. If it persists, please, open a new issue with all the debugging information. But first try not to be too invasive when [overriding controllers](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs#overwriting-controllers), or you can end up disabling `devise` and `devise-jwt` in the way.

**Comment by brentkearney** [comment]
With devise-jwt 0.5.9 and Rails 5.2.2, I have the same or similar issue. The :authenticate_user! filter in the controller does not return true. I'm using the JTIMatcher strategy instead of Whitelist.

Controller:
```
class WelcomeController < ApplicationController
  before_action :authenticate_user!
...
```

Model:
```
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :registerable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable, :confirmable, :invitable,
         :jwt_authenticatable, jwt_revocation_strategy: self
...
```

Request test:
```
require 'rails_helper'
require 'devise/jwt/test_helpers'

RSpec.describe 'Sign-in', type: :request do
  let(:user) { create(:user) }
  let(:url) { user_session_url }
  let(:params) do
    {
      user: {
        email: user.email,
        password: user.password
      }
    }
  end

  context 'With valid credentials' do
    before do
      headers = { 'Accept' => 'application/json', 'Content-Type' => 'application/json' }
      auth_headers = Devise::JWT::TestHelpers.auth_headers(headers, user)
      post url, params: params.merge(auth_headers)
    end

    it 'returns 200' do
      expect(response).to have_http_status(200)
    end
...
```

From the test logs I can see that it authenticates properly:
`UPDATE "users" SET "current_sign_in_at" = $1...`

And inspecting the response, it looks like the JWT token was set:
`"action_dispatch.request.unsigned_session_cookie"=>{"session_id"=>"8b76ac403895b2e596617a2bbc9c467f"}, "warden-jwt_auth.token"=>"eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJhYWIyZjQwZS0wMDhhLTRiMjgtYWI1Yi0zNGM0NDM1MjhhZWQiLCJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNTYxNTg2NjI0LCJleHAiOjE1NjE1OTAyMjR9.k7xmanHLZH1vuxAy_fC8CwzdAWOSUQde-76XcJpASFg"...`,

But Rails redirects to the sign-in page when it hits the `:authenticate_user! filter` in WelcomeController. How do I fix this? Thank you!

**Comment by sevgibson** [comment]
Interesting -- I was experiencing the issue described by @jovanmaric . I was able to find that during execution of rspec, warden-jwt was raising an error with `wrong aud`.

It turns out, the method `auth_headers = Devise::JWT::TestHelpers.auth_headers(headers, user, aud: "AppName")` was not adding the audience to the auth_headers, and even when I added ``headers["JWT_AUD"] = "AppName"`` myself, it failed to work (`wrong aud`),

Further research led me to [this line](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/env_helper.rb#L56) and so, I changed `headers["JWT_AUD"] = "AppName"` to `headers["HTTP_JWT_AUD"] = "AppName"` and then it worked.

Somewhere in rspec => racc (I am not smart enough to know where), the header `Authorization` becomes 'HTTP_AUTHORIZATION', but this does not happen with `JWT_AUD`. This does happen correctly within development however, so as long as I set `HTTP_JWT_AUD`, it works.

No help is required, but in case others stumble onto this issue, I wanted to let you know what I found.
Also, there may be some bugfix to be made in the context of the test helper.
